### ISSUE TITLE
Thermo group additivity estimations are off for N#C-R species

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-database#151]
Group additivity values for HCN (SMILES: `N#C`) are off compared to `thermo_DFT_CCSDTF12_BAC` and other libraries. This affects many `N#C-R` groups, as recently brought up by @nyee in an RMG subgroup meeting.
Current thermo group additivity estimation for HCN is: `group(Ct-CtCs) + other(R) + group(N) + other(R)`
![untitled-1](https://cloud.githubusercontent.com/assets/16158262/21318645/0930635a-c5d8-11e6-94ec-0f2c043e1709.jpg)

**Comment by nyee** [comment]
Fixed by #163

**Comment by alongd** [comment]
I'm not sure we should close this yet.
Searching for `N#C` on the website still gives a bad GAV estimate.

**Comment by nyee** [comment]
@alongd  I tried it with the thermoestimator in RMG and it is pretty close. The problem with the website is that it has not been updated since we pulled in nitrogen.

**Comment by alongd** [comment]
I see. I though the website is automatically synced with official/master. Thanks!

**Comment by nyee** [comment]
Yeah it's not automatic, Max has to manually do it. If you look at the bottom of the website you can see the last time it was updated with the official branches.
