### ISSUE TITLE
Waddington reaction and oxidation of aldehyde to carboxylic acid

### ISSUE THREAD

**Issue by duychem** [ReactionMechanismGenerator/RMG-database#197]
Hi. Could anyone can help me to answer this question, please?
Do these reactions below are recognized automatically in RMG ?: 
- Waddington reaction: RCH(OH)CH(OO•)R'= RCHO + R'CHO + OH•
- Oxidation of aldehyde to carboxylic acid: RCHO = RCOOH

**Comment by nyee** [comment]
Waddington is not implemented as a family. For the second one, we do not have that as a one step reaction. Is that multi-step? RMG may be able to find a pathway there eventually, but I doubt it would be very simple.

For one step reactions, you can always check on rmg.mit.edu under kinetics search to see if RMG finds an example reaction.
