### ISSUE TITLE
Undocumented kinetics in 1,2-Birad_to_alkene Family

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-database#231]
This family currently has no training reactions and all kinetic data comes from rules only.
All rules, except for a default value, have the following short description: `see references header of 1,2-Birad_to_alkene/rateLibrary.txt`.
I couldn't locate the `rateLibrary.txt` file anywhere, even when searching the history of this folder. Probably comes from RMG-Java.
I'd expect the rates in this family to be much higher, and the current values have no justification / explanation.

**Comment by alongd** [comment]
The relevant [`rateLibrary.txt`](https://github.com/ReactionMechanismGenerator/RMG-Java/blob/master/databases/RMG_database/kinetics_groups/1%2C2-Birad_to_alkene/rateLibrary.txt) file is indeed in the RMG-Java Repo. So technically RMG-Py's database has no explanation to the rates used.

**Comment by gmagoon** [comment]
Why do you expect the rates to be higher?

**Comment by alongd** [comment]
I now see your documented explanation in Java, which is very thorough and appreciated!

We're adding sulfur chemistry, and in particular we are considering transitions such as:
![image](https://user-images.githubusercontent.com/16158262/34002901-e39fa208-e0c1-11e7-9af3-3fba8dce84a8.png) <=> ![image](https://user-images.githubusercontent.com/16158262/34002911-eae68d1a-e0c1-11e7-8bb4-11e9c05287d8.png)
and:
![image](https://user-images.githubusercontent.com/16158262/34002762-803285aa-e0c1-11e7-8c55-cd5a00b31632.png) <=> ![image](https://user-images.githubusercontent.com/16158262/34002775-8c5056b4-e0c1-11e7-8012-e92a7ec7370e.png)
but also:
![image](https://user-images.githubusercontent.com/16158262/34002992-1918ab50-e0c2-11e7-8563-3e9aa81af5a2.png) <=> ![image](https://user-images.githubusercontent.com/16158262/34003000-1ebc634e-e0c2-11e7-8d85-7b72e5300015.png)

We're considering to elaborate this family to include heteroatoms in a similar transition. Since the above transitions are of an excited structure to its ground state, I do expect the rates to be relatively fast (just a few collisions with the bath gas, so the excited states shouldn't have much time to react in other pathways).

Perhaps it's a different case than the C/H chemistry in the current 1,2,-Birad_to_alkene family, although the template is the same?
I'll try to asses the rates in my case and see how different they are.

**Comment by alongd** [comment]
Closed via #232
