### ISSUE TITLE
New families need drawings

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-database#244]
A few new families have been added recently that don't have drawings yet:
- 2+2_cycloaddition_CS
- Cyclic_Thioether_Formation
- Singlet_Val6_to_triplet

Once the drawings in the families folder are updated, the [families page on the website](http://rmg.mit.edu/database/kinetics/families/) can be as well.

**Comment by alongd** [comment]
Is there a tool we use for these drawings, or should I exercise my creativity here?

**Comment by mliu49** [comment]
Closed by #245.
