### ISSUE TITLE
Reverse direction training reactions with poorly estimated thermo

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-database#249]
I've noticed at least one (and I suspect there are more, because this is such an easy mistake to make) training reaction with heteroatoms that is in the reverse direction to the family.  Since we can't estimate N and S thermo very well if someone does not include libraries for N,S thermo when the rate is reversed before putting it in the tree it can be drastically off.  

Ex:  
CC[O] + [O] = CCO[O]  is currently estimated using the reverse of SO[O] = S[O] + [O].  This gave me rates about 10 orders of magnitude faster for CCO[O] => CC[O] + [O] than what I found in literature.  
We either need to comment these rates out or adjust the trees so they can't be used for C,O,H chemistry.

**Comment by alongd** [comment]
@mjohnson541, is this in the Birad_R_Rec family? I couldn't find this reaction in the training, can you point it out?

**Comment by mjohnson541** [comment]
Yes:  
entry(
   index = 3,
   label = "HSOO <=> HSO + O",
   degeneracy = 1,
   kinetics = Arrhenius(A=(2.01e+19, 's^-1'), n=-1.07, Ea=(28377, 'cal/mol'), T0=(1, 'K'), Tmin = (200, 'K'), Tmax = (2000, 'K')),
   rank = 2,
   shortDesc = u"""Training reaction from kinetics library: SOx""",
   longDesc =
u"""
T range: 200-2000 K
A. Goumri, J-D.R. Rocha, D. Laakso, C.E. Smith, P. Marshall, J. Phys. Chem. A, 1999, 103(51), 11328-11335 doi: 10.1021/jp9924070
Table 7 on p. 11333
calculations done at the QCISD(T)/6-311+G(3df,2p)//MP2=FULL/6-31G(d) level of theory
Originally a Troe expression was given, only k_inf is taken here
""",
)

**Comment by alongd** [comment]
Right! I didn't read the reaction correctly.
This (and another) training reaction were commented out until recently, and the author (me) thought it could be un-commented since now we have good thermo, see 5a4d24e1d2600df15a0a73f033c3957b443c84a3.
You are right that HSOO's thermo is from a library, and that GAV for sulfur still requires improvements.

**Comment by alongd** [comment]
closed via #250
