### ISSUE TITLE
Literature GAV for chlorine-containing groups are not in accord with what RMG expects

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-database#254]
We're trying to add GAV to represent chlorinated hydrocarbons, however there's a mismatch between the way relevant literature groups are defined and what RMG expects to find.
For example, consider dichloroethane:
![image](https://user-images.githubusercontent.com/16158262/37155058-e529e45a-22af-11e8-96cc-4f273d0e8e18.png)
The literature group that represents this is `Cs-ClHH` (accounted for twice). However, RMG also looks for respective groups for the Cl atoms themeselves. In other words, the literature groups treat Cl's the way we treat H's and don't specify them as seperate groups, but rather account for them within the major carbon group. As mentioned above, this is not what RMG expects to find.

We could resolve this in several ways:
- Add dummy groups for these Cl atoms with zeroes as a convention (and document/explain this)
  **pros:** relatively easy
- Change the code in -Py so that halogens are treated like H's as far as GAV is concerned.
  **cons:** we won't be able to represent GAV for Cl/halogens in the future. Besides, what about things like `HCl`?
- Regenerate the groups so they are consistent with what RMG expects.
  **cons:** not trivial. **pros:** a permanent and robust solution.

Please let me know what you think of the above.

tag @mjohnson541, @zjburas

**Comment by zjburas** [comment]
For the small molecules like Cl, HCl and Cl2 we can just rely on a thermo library, analogous to how H and H2 are treated. In fact, all three small Cl-containing species are already included in primaryThermoLibrary. 

If you're worried about generalizing to halogens that can form more than one bond, maybe that could be addressed by different atomTypes. So the halogen atomTypes that can form only one bond are treated like hydrogen, but others don't have that restriction.

For transparency, I think it's better if we don't refit the groups. That way we can always just point to Benson's book as the source of the groups.

**Comment by alongd** [comment]
OK. Perhaps we'll use option 1 of having dummy groups instead of changing the GAV code specifically for monovalent halogens? As long as we're consistent and explain it in the groups' descriptions, that could be OK. (we won't be able to have some groups that include the Cl atoms and some which don't and require the same Cl correction with real data)

**Comment by mjohnson541** [comment]
I think the dummy groups are a good short term solution for now.  In the long run I think we'll want to either refit the groups or move to the neural net estimator, but I don't think we have reason to worry about those right now.

**Comment by zjburas** [comment]
Ok, I'll add the dummy group today and test it out.

**Comment by mliu49** [comment]
I assume this was already implemented in #257?

**Comment by alongd** [comment]
Right
