### ISSUE TITLE
Universal Database for both RMG-Py and RMG-Java

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-database#29]
We just discussed (again) forming a universal database structure for both RMG-Py and RMG-Java. Here are my notes from the videoconference. Add discussion and development notes below...

**Universal Database**

   * human editable and readable
      * look more like a spreadsheet - eg. one line per reaction.
      * minimize boilerplate
      * excel sheets? csv? 
      * benefit of plan text
         * editable using emacs over ssh
         * works with git

   * should store
      * dictionary in new 4-column adjacency list with explicit hydrogens
      * comments
      * uncertainties
      * confidences
      * libraries
      * rules
      * groups
      * depositories (actual reactions, with labeled atoms)

   * exportable to Java
      * remove N and fourth column
      * or modify Java so it can parse the universal database

   * exportable to Python
      * use "import to database" script,
      * or make it read the universal database
      * modify the .load() methods

   * Instead of exporting, Make both read the universal database
      * Java could ignore the extra column in the adjacency list, and all N atom types
      * Benefit: people won't be tempted to edit the exported database!
      * Should be designed so new features are backwards compatible, 
         * perhaps programs ignore stuff they don't understand
         * eg. temperature-dependent viscosity parameters in solvent database.
         * transition state estimate databases
         * new atom types
      * Possible drawback
         * risk slowing development of new features (barrier: have to implement in both)
         * or keep breaking RMG-Java

**Comment by connie** [comment]
Java is dead.
