### ISSUE TITLE
New R_Recombination rules much too fast?

### ISSUE THREAD

**Issue by shenghuiqin** [ReactionMechanismGenerator/RMG-database#353]
(Issue drafted by/with @rwest)

After the automatically generated R_Recombination rules in PR #334 
the reaction
`C[C]=CC=C + [H]  <=> CC=CC=C` 
gives this reaction rate
```
! Reaction index: Chemkin #7387; RMG #8750
! Template reaction: R_Recombination
! Flux pairs: C5H7(2097), C5H8(545); H(3)(1), C5H8(545); 
! BM rule fitted to 2 training reactions at node Root_1R->H_N-2R-inRing_N-2R->H_N-2CNOS->S_2CNO->C_Ext-2C-R_Sp-3R!H=2C_Ext-2C-R_Ext-3R!H-R
!     Total Standard Deviation in ln(k): 11.5401827615
! Exact match found for rate rule [Root_1R->H_N-2R-inRing_N-2R->H_N-2CNOS->S_2CNO->C_Ext-2C-R_Sp-3R!H=2C_Ext-2C-R_Ext-3R!H-R]
! Euclidian distance = 0
! family: R_Recombination
H(3)(1)+C5H7(2097)=C5H8(545)                        1.554090e+97 -24.703   0.000    
```
hitting this rate rule:
https://github.com/ReactionMechanismGenerator/RMG-database/pull/334/files#diff-2553ec1602f5d95579cd517d15efcaa5R1734

The [old rate](https://rmg.mit.edu/database/kinetics/reaction/reactant1=multiplicity%202%0A1%20H%20u1%20p0%20c0%0A__reactant2=multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B5,S%7D%20%7B6,S%7D%20%7B7,S%7D%20%7B8,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B4,D%7D%20%7B9,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B5,D%7D%20%7B10,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B11,S%7D%20%7B12,S%7D%0A5%20%20C%20u1%20p0%20c0%20%7B1,S%7D%20%7B3,D%7D%0A6%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A7%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B2,S%7D%0A10%20H%20u0%20p0%20c0%20%7B3,S%7D%0A11%20H%20u0%20p0%20c0%20%7B4,S%7D%0A12%20H%20u0%20p0%20c0%20%7B4,S%7D%0A__product1=1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B6,S%7D%20%7B7,S%7D%20%7B8,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,D%7D%20%7B9,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B2,D%7D%20%7B4,S%7D%20%7B11,S%7D%0A4%20%20C%20u0%20p0%20c0%20%7B3,S%7D%20%7B5,D%7D%20%7B10,S%7D%0A5%20%20C%20u0%20p0%20c0%20%7B4,D%7D%20%7B12,S%7D%20%7B13,S%7D%0A6%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A7%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A8%20%20H%20u0%20p0%20c0%20%7B1,S%7D%0A9%20%20H%20u0%20p0%20c0%20%7B2,S%7D%0A10%20H%20u0%20p0%20c0%20%7B4,S%7D%0A11%20H%20u0%20p0%20c0%20%7B3,S%7D%0A12%20H%20u0%20p0%20c0%20%7B5,S%7D%0A13%20H%20u0%20p0%20c0%20%7B5,S%7D%0A__res=True) is about 10^13 cm3/mol/s.   (10^7 m3/mol/s), about the collision limit.

The new one is (back of the envelope estimate) 10^(97-75)=10^22 cm3/mol/s at 1000K and 10^(97-50)=10^47 cm3/mol/s at 100K.

This is just one example. There are many reactions showing up with rates far exceeding the collision limit, causing stiffness issues.

Any suggestions?

**Comment by mjohnson541** [comment]
One of the training reactions involved in this rule looks quite suspicious: 
<img width="298" alt="Screen Shot 2019-09-03 at 4 10 04 PM" src="https://user-images.githubusercontent.com/7773228/64205152-5388be00-ce65-11e9-8ef3-1175aa3f5250.png">
Entry:  
entry(
    index = 32,
    label = "C10H9 <=> C10H8 + H",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.89e+16, 's^-1'), n=-0.28, Ea=(68.378, 'kcal/mol'), T0=(1, 'K')),
    rank = 5,
    shortDesc = u"""Training reaction from kinetics library: First_to_Second_Aromatic_Ring/2016_Mebel_C10H9_highP""",
    longDesc = 
u"""
Taken from entry: W111 <=> P114 + H
""",
)

**Comment by rwest** [comment]
Hmm. The rate definition from Mebel 2016 is in the bond-breaking direction. I wonder what thermodynamics RMG assumed when reversing it to get the rate of recombination....  I wouldn't be surprised if it was garbage (pretty tricky delocalization to get right there...)
