### ISSUE TITLE
H2CC adjlist incorrect in many libraries

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-database#365]
I think many libraries incorrectly have the triplet form of H2CC rather than the singlet form (i.e. vinylidene).

This is readily apparent if you look up the thermo for [triplet H2CC](https://rmg.mit.edu/database/thermo/molecule/multiplicity%203%0A1%20C%20u2%20p0%20c0%20%7B2,D%7D%0A2%20C%20u0%20p0%20c0%20%7B1,D%7D%20%7B3,S%7D%20%7B4,S%7D%0A3%20H%20u0%20p0%20c0%20%7B2,S%7D%0A4%20H%20u0%20p0%20c0%20%7B2,S%7D%0A). We see a ~50 kcal/mol difference between DFT_QCI_thermo/GAV and all of the other libraries. DFT_QCI_thermo is the only library with data for both singlet and triplet forms.

Additionally, comparing against the thermo for [singlet H2CC](https://rmg.mit.edu/database/thermo/molecule/1%20C%20u0%20p1%20c0%20%7B2,D%7D%0A2%20C%20u0%20p0%20c0%20%7B1,D%7D%20%7B3,S%7D%20%7B4,S%7D%0A3%20H%20u0%20p0%20c0%20%7B2,S%7D%0A4%20H%20u0%20p0%20c0%20%7B2,S%7D%0A) shows suspiciously similar enthalpies.

The corresponding kinetics libraries of the incorrect thermo libraries likely also have the same issue.

**Comment by PWstmrlnd** [comment]
I'm sure you are right. SMILES and InChI don't allow distinction of electronic states, do they? That's an identity problem for all kinds of carbene data.
