### ISSUE TITLE
Error O-NH2_ads in surfaceThermoPt library

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-database#380]
There must be a mistake in the polynomials, which is giving a very bad entropy
https://rmg.mit.edu/database/thermo/libraries/surfaceThermoPt/10/

https://rmg.mit.edu/database/thermo/molecule/1%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B5,S%7D%0A2%20N%20u0%20p1%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B4,S%7D%0A3%20H%20u0%20p0%20c0%20%7B2,S%7D%0A4%20H%20u0%20p0%20c0%20%7B2,S%7D%0A5%20X%20u0%20p0%20c0%20%7B1,S%7D%0A

<img width="667" alt="Screen Shot 2020-01-13 at 12 29 41 PM" src="https://user-images.githubusercontent.com/93807/72277772-8c4d5680-3600-11ea-956d-78881a944a5d.png">

Unfortunately this is then messing up reverse rate constant calculations down the line, and making our simulations crash.

**Comment by rwest** [comment]
Browsing through, saw at least one other discontinuous curve
https://rmg.mit.edu/database/thermo/libraries/surfaceThermoPt/3/

We should have something in the automated database tests to catch these.

**Comment by mazeau** [comment]
I just went through and these 2 are the only ones with discontinuities in surfaceThermoPt

**Comment by kblondal** [comment]
H2_ads: a5 for 1000-2000K is missing a minus sign, so it should be -1.89108x10^3
O-NH2_ads: a6 for range 298-1000K is supposed to be -7.56970401E+00, but it is -7.56970401E+001 for O-NH2 in the database file, causing the discontinuity. I'll make a pull request for these fixes.
