### ISSUE TITLE
Catalytic surface rates need fixing in new vdW reaction families.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-database#430]
**Observation:**
Models which previously demonstrated catalytic combustion of methane is now (with the new reaction families proposed in https://github.com/ReactionMechanismGenerator/RMG-database/pull/385 ) doing partial oxidation, probably due to sparse training data in surface dissociation vdW. Specifically, vdW adsorbed CH4 is dissociating to CH3X and HX using an inappropriate rate estimate (based on cleaving an OH bond in methanol on Cu?), because we don't have a more appropriate rate.

**Recollection:**
When we first entered kinetic data from Deutchmann, at the time we couldn't do vdW stuff so we skipped those data, sometimes pretending things went directly from to or from the gas phase rather than via a vdW complex.

**Suggestion:** 
go back the Deutschmann paper(s) that initially gave us the rates, and enter the vdW rates properly, in the new families. Also, remove any fictitious rates that we entered to take their place (eg. _if_ we had previously replaced `A + X -> AvdwX -> BX + CX` with `A -> BX + CX` then as well as adding the correct `A + X -> AvdwX` and `AvdwX -> BX + CX` reactions, we should also remove the `A -> BX + CX` rate that we made up.)

Example papers we should mine for data:

- Delgado, K.H.; Maier, L.; Tischer, S.; Zellner, A.; Stotz, H.; Deutschmann, O. Surface Reaction Kinetics of Steam- and CO2-Reforming as Well as Oxidation of Methane over Nickel-Based Catalysts. Catalysts 2015, 5, 871-904.  https://doi.org/10.3390/catal5020871  Table 3 
- Maier, L., Schädel, B., Herrera Delgado, K. et al. Steam Reforming of Methane Over Nickel: Development of a Multi-Step Surface Reaction Mechanism. Top Catal 54, 845 (2011). https://doi.org/10.1007/s11244-011-9702-1

_This issue based on discussion with @kblondal and @cfgoldsmith. Hoping @mazeau can take a look and perhaps solve with extra commits to https://github.com/ReactionMechanismGenerator/RMG-database/pull/385_

**Comment by rwest** [comment]
I'm not sure that the italicized part of this issue has been addressed:
> go back the Deutschmann paper(s) that initially gave us the rates, and enter the vdW rates properly, in the new families. **_Also, remove any fictitious rates that we entered to take their place (eg. if we had previously replaced A + X -> AvdwX -> BX + CX with A -> BX + CX then as well as adding the correct A + X -> AvdwX and AvdwX -> BX + CX reactions, we should also remove the A -> BX + CX rate that we made up.)_**
@mazeau please could you check and perhaps re-open this issue (or make a new one) if needed?

**Comment by mazeau** [comment]
So this is realated to Reviewer 2's comment about 
> Is there a gaseous O2 adsorption on Rh surface before dissociation? Seem that the O2(g) + *--> O2(s) step is missing in table 1. 

..because it's currently commented out because it's a special case
