### ISSUE TITLE
Surface_EleyRideal_Addition_Multiple_Bond reverse template matches bidentate adsorbates

### ISSUE THREAD

**Issue by Tingchenlee** [ReactionMechanismGenerator/RMG-database#448]
Surface_EleyRideal_Addition_Multiple_Bond should match the reaction of an adsorbate with a gas phase molecule, but the reverse template matches a bidentate adsorbate, so when the recipe is applied in reverse, it ends up with two adsorbates. Then when it tries to generate the forward kinetics (to get the degeneracy) it crashes.

Eg this is valid
![image](https://user-images.githubusercontent.com/56702445/100886746-2cfb6d80-3482-11eb-9c09-432650fec726.png)

but this should not be
![image](https://user-images.githubusercontent.com/56702445/100886662-1523e980-3482-11eb-86fc-7e6cf5bb3c1c.png)

**Comment by mazeau** [comment]
Canyou attach the input file and let me know which version of rmg database and rmg you're using?

El dic. 2, 2020, a la(s) 09:39, Ting-Chen <notifications@github.com> escribió:

﻿

Surface_EleyRideal_Addition_Multiple_Bond should match the reaction of an adsorbate with a gas phase molecule, but the reverse template matches a bidentate adsorbate, so when the recipe is applied in reverse, it ends up with two adsorbates. Then when it tries to generate the forward kinetics (to get the degeneracy) it crashes.

Eg this is valid
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F56702445%2F100886746-2cfb6d80-3482-11eb-9c09-432650fec726.png&data=04%7C01%7Cmazeau.e%40northeastern.edu%7Ce356b580c49647771eae08d896d01daf%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637425167882661210%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JG4wNmTZzSWXKO2z0jPFcS%2BDfE3Y6Xbu%2BGREYK91kOg%3D&reserved=0>

but this should not be
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F56702445%2F100886662-1523e980-3482-11eb-86fc-7e6cf5bb3c1c.png&data=04%7C01%7Cmazeau.e%40northeastern.edu%7Ce356b580c49647771eae08d896d01daf%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637425167882661210%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=veuCFQJO2grnYUM0%2BsDD%2FSS5XxqDOq5lBTGlybJ9W4I%3D&reserved=0>

**Comment by rwest** [comment]
It's not that a labeled atom (the N in the example above)  _is_ a surface site, just that it is _attached_ to one.

**Comment by mazeau** [comment]
> It's not that a labeled atom (the N in the example above) _is_ a surface site, just that it is _attached_ to one.

Right, I guess I thought `R` would only match gas phase things or else families like surface_adsorption would also run into the same issue where the species adsorbing could also be attached to a surface site.  There is nothing stopping the same thing from happening there that I can think of

**Comment by Tingchenlee** [comment]
Sorry for the late update!
**RMG-Py:** debugcat  https://github.com/ReactionMechanismGenerator/RMG-Py/tree/debugcat
**RMG-database:** ammonia_version2 https://github.com/Tingchenlee/RMG-database/tree/ammonia_version2
**Input.py:**
```python
database(
    thermoLibraries=['surfaceThermoPt111', 'primaryThermoLibrary'],
    reactionLibraries = ['Surface/CPOX_Pt/Deutschmann2006','Surface/Ammonia_Ru0001'],  
    seedMechanisms = [],  
    kineticsDepositories = ['training'],
    kineticsFamilies = ['surface','default'],
    kineticsEstimator = 'rate rules',
)

catalystProperties(
    bindingEnergies = {  # default values for Ru(0001)  
    		              'H':(-2.85191775E+00, 'eV/molecule'),
                          'C':(-7.59790076E+00, 'eV/molecule'),
                          'N':(-5.96899731E+00, 'eV/molecule'),
                          'O':(-5.44919557E+00, 'eV/molecule'),
                      },
    surfaceSiteDensity=(2.630E-09, 'mol/cm^2'), 
)

species(
    label='H2',
    reactive=True,
    structure=SMILES("[H][H]"),
)

species(
    label='N2',
    reactive=True,
    structure=SMILES("N#N"),
)

species(
    label='X',
    reactive=True,
    structure=adjacencyList("1 X u0"),
)

surfaceReactor(  
    temperature=(723,'K'),
    initialPressure=(200.0, 'bar'),
    initialGasMoleFractions={
        "H2": 0.67,
        "N2": 0.33,
    },
    initialSurfaceCoverages={
        "X": 1.0,
    },
    surfaceVolumeRatio=(1.e5, 'm^-1'),
    terminationConversion = { "N2":0.80,},
    terminationTime=(0.1, 's'),
)

simulator(
    atol=1e-18,
    rtol=1e-12,
)

model( 
    toleranceKeepInEdge=0.0,
    toleranceMoveToCore=0.0000000001, 
    toleranceInterruptSimulation=1,
    maximumEdgeSpecies=100000,
    minCoreSizeForPrune=150,
    toleranceThermoKeepSpeciesInEdge=0.5, 
    minSpeciesExistIterationsForPrune=4,
)

options(
    units='si',
    saveRestartPeriod=None,
    generateOutputHTML=True,
    generatePlots=True, 
    saveSimulationProfiles=True,
)

```

**Comment by Tingchenlee** [comment]
This issue only happened in Surface/Ammonia_Ru0001 and Surface/Ammonia_Ru_MgAl2O2. I had tried other libraries and they didn't have these error messages.

**Comment by rwest** [comment]
> > It's not that a labeled atom (the N in the example above) _is_ a surface site, just that it is _attached_ to one.
> 
> Right, I guess I thought `R` would only match gas phase things or else families like surface_adsorption would also run into the same issue where the species adsorbing could also be attached to a surface site. There is nothing stopping the same thing from happening there that I can think of

Right - we had to add stuff to the RMG-Py source code to ensure adsorption reactions couldn't apply to adsorbates. 
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/81970c3c94c14cb24580e1164adcf8f2bb9fee8f/rmgpy/data/kinetics/family.py#L1966
And for desorbing half of a bidentate we added this
https://github.com/ReactionMechanismGenerator/RMG-Py/blob/81970c3c94c14cb24580e1164adcf8f2bb9fee8f/rmgpy/data/kinetics/family.py#L2214

Maybe you can invent a better way.

**Comment by mazeau** [comment]
created a new branch to deal with this issue here https://github.com/ReactionMechanismGenerator/RMG-Py/tree/surfacedebug

**Comment by mazeau** [comment]
I've been trying to replicate that error message and have had no luck. 

I get this now, after running on the rebased `ammonia_version2` and `debugcat`:
```
  File "/Users/emilymazeau/Code/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/Users/emilymazeau/Code/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/rmg/main.py", line 732, in execute
    trimolecular_react=self.trimolecular_react)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/rmg/model.py", line 614, in enlarge
    self.apply_thermo_to_species(procnum)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/rmg/model.py", line 824, in apply_thermo_to_species
    self.generate_thermo(spc, rename=True)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/rmg/model.py", line 831, in generate_thermo
    submit(spc, self.solvent_name)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 175, in submit
    spc.thermo = evaluator(spc, solvent_name=solvent_name)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 160, in evaluator
    thermo = generate_thermo_data(spc, solvent_name=solvent_name)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 125, in generate_thermo_data
    thermo0 = thermodb.get_thermo_data(spc)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/data/thermo.py", line 1223, in get_thermo_data
    thermo0 = self.get_thermo_data_for_surface_species(species)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/data/thermo.py", line 1578, in get_thermo_data_for_surface_species
    thermo = min(thermo_models, key=lowest_energy)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/data/thermo.py", line 1576, in lowest_energy
    return thermo_model.H298.value
AttributeError: 'rmgpy.thermo.nasa.NASA' object has no attribute 'H298'
```

**Comment by mazeau** [comment]
More error messages! When running on rmgpy `master` and rmgdatabase `ammonia_version2`:

```
For reaction generation 1 process is used.
Generating thermo for new species...
Error: Could not update atomtypes for this molecule:
multiplicity 1
1 N u1 p0 c0 {2,S} {3,T}
2 N u0 p1 c0 {1,S} {4,D}
3 N u2 p0 c0 {1,T}
4 N u0 p1 c0 {2,D} {5,S}
5 H u0 p0 c0 {4,S}

Error: Error attempting to get thermo for species N=NN(N=[Pt])[Pt](40) with structure 
1 N u0 p1 c0 {2,S} {3,S} {6,S}
2 N u0 p1 c0 {1,S} {4,D}
3 N u0 p1 c0 {1,S} {7,D}
4 N u0 p1 c0 {2,D} {5,S}
5 H u0 p0 c0 {4,S}
6 X u0 p0 c0 {1,S}
7 X u0 p0 c0 {3,D}

Traceback (most recent call last):
  File "/Users/emilymazeau/Code/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/Users/emilymazeau/Code/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/rmg/main.py", line 922, in execute
    trimolecular_react=self.trimolecular_react)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/rmg/model.py", line 614, in enlarge
    self.apply_thermo_to_species(procnum)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/rmg/model.py", line 824, in apply_thermo_to_species
    self.generate_thermo(spc, rename=True)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/rmg/model.py", line 831, in generate_thermo
    submit(spc, self.solvent_name)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 175, in submit
    spc.thermo = evaluator(spc, solvent_name=solvent_name)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 160, in evaluator
    thermo = generate_thermo_data(spc, solvent_name=solvent_name)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 125, in generate_thermo_data
    thermo0 = thermodb.get_thermo_data(spc)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/data/thermo.py", line 1223, in get_thermo_data
    thermo0 = self.get_thermo_data_for_surface_species(species)
  File "/Users/emilymazeau/Code/RMG-Py/rmgpy/data/thermo.py", line 1547, in get_thermo_data_for_surface_species
    dummy_molecule.update()
  File "rmgpy/molecule/molecule.py", line 1137, in rmgpy.molecule.molecule.Molecule.update
  File "rmgpy/molecule/molecule.py", line 1362, in rmgpy.molecule.molecule.Molecule.update_atomtypes
  File "rmgpy/molecule/molecule.py", line 1357, in rmgpy.molecule.molecule.Molecule.update_atomtypes
  File "rmgpy/molecule/atomtype.py", line 813, in rmgpy.molecule.atomtype.get_atomtype
  File "rmgpy/molecule/atomtype.py", line 841, in rmgpy.molecule.atomtype.get_atomtype
rmgpy.exceptions.AtomTypeError: Unable to determine atom type for atom N., which has 1 single bonds, 0 double bonds (0 to O, 0 to S, 0 others), 1 triple bonds, 0 quadruple bonds, 0 benzene bonds, 0 lone pairs, and +0 charge.
```

**Comment by Tingchenlee** [comment]
I think the 
```
AttributeError: 'rmgpy.thermo.nasa.NASA' object has no attribute 'H298'
```
was caused by the current progress of this PR
https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2045
The second error
```
rmgpy.exceptions.AtomTypeError: Unable to determine atom type for atom N., which has 1 single bonds, 0 double bonds (0 to O, 0 to S, 0 others), 1 triple bonds, 0 quadruple bonds, 0 benzene bonds, 0 lone pairs, and +0 charge.
```
had happened here before: 
https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2039

I made a new branch of RMG-Py:
https://github.com/Tingchenlee/RMG-Py/tree/debug448
Can probably reproduce the error by using this RMG-Py branch and the input file here:
```python
database(
    thermoLibraries=['surfaceThermoPt111', 'primaryThermoLibrary'],
    reactionLibraries = ['Surface/CPOX_Pt/Deutschmann2006'],  
    seedMechanisms = [],  
    kineticsDepositories = ['training'],
    kineticsFamilies = ['surface','default'],
    kineticsEstimator = 'rate rules',
)

catalystProperties(
    bindingEnergies = {  # default values for Ru(0001)  
    		          'H':(-2.85191775E+00, 'eV/molecule'),
                          'C':(-7.59790076E+00, 'eV/molecule'),
                          'N':(-5.96899731E+00, 'eV/molecule'),
                          'O':(-5.44919557E+00, 'eV/molecule'),
                      },
    surfaceSiteDensity=(2.630E-09, 'mol/cm^2'), 
)

species(
    label='H2',
    reactive=True,
    structure=SMILES("[H][H]"),
)

species(
    label='N2',
    reactive=True,
    structure=SMILES("N#N"),
)

species(
    label='X',
    reactive=True,
    structure=adjacencyList("1 X u0"),
)

surfaceReactor(  
    temperature=(723,'K'),
    initialPressure=(200.0, 'bar'),
    initialGasMoleFractions={
        "H2": 0.67,
        "N2": 0.33,
    },
    initialSurfaceCoverages={
        "X": 1.0,
    },
    surfaceVolumeRatio=(1.e5, 'm^-1'),
    terminationConversion = { "N2":0.80,},
    terminationTime=(0.1, 's'),
)

simulator(
    atol=1e-18,
    rtol=1e-12,
)

model( 
    toleranceKeepInEdge=0.0,
    toleranceMoveToCore=0.0000000001, 
    toleranceInterruptSimulation=1,
    maximumEdgeSpecies=100000,
    minCoreSizeForPrune=150,
    toleranceThermoKeepSpeciesInEdge=0.5, 
    minSpeciesExistIterationsForPrune=4,
)

options(
    units='si',
    saveRestartPeriod=None,
    generateOutputHTML=True,
    generatePlots=True, 
    saveSimulationProfiles=True,
)
```

**Comment by kblondal** [comment]
I was able to reproduce the error for a different species, bidentate CO running with the master branch and the latest database branch for methane catalytic combustion:
```Error: Product: Species(label="", molecule=[Molecule(smiles="[Pt]OC=[Pt]")], molecular_weight=(29.018,'amu'))
Traceback (most recent call last):
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmgpy/rmg/main.py", line 922, in execute
    trimolecular_react=self.trimolecular_react)
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmgpy/rmg/model.py", line 599, in enlarge
    procnum=procnum)
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmgpy/rmg/react.py", line 172, in react_all
    return react(spc_fam_tuples, procnum), [fam_tuple[0] for fam_tuple in spc_fam_tuples]
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmgpy/rmg/react.py", line 66, in react
    reactions = list(map(_react_species_star, spc_fam_tuples))
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmgpy/rmg/react.py", line 79, in _react_species_star
    return react_species(*args)
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmgpy/rmg/react.py", line 94, in react_species
    reactions = get_db('kinetics').generate_reactions_from_families(species_tuple, only_families=only_families)
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmgpy/data/kinetics/database.py", line 537, in generate_reactions_from_families
    reaction_list = find_degenerate_reactions(reaction_list, same_reactants, kinetics_database=self)
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmgpy/data/kinetics/common.py", line 333, in find_degenerate_reactions
    rxn.degeneracy = family.calculate_degeneracy(rxn)
  File "/home/kblondal/Dropbox/Code/Main/RMG-Py/rmgpy/data/kinetics/family.py", line 1876, in calculate_degeneracy
    'but generated {2}').format(reaction, self.label, len(reactions)))
rmgpy.exceptions.KineticsError: Unable to calculate degeneracy for reaction [Pt] + O=C=[Pt] <=> [Pt]OC=[Pt] in reaction family Surface_EleyRideal_Addition_Multiple_Bond. Expected 1 reaction but generated 0
```

I got rid of the error by modifying family.py in the same way as avoiding desorbing half of a bidentate based on the link @rwest sent: https://github.com/ReactionMechanismGenerator/RMG-Py/blob/81970c3c94c14cb24580e1164adcf8f2bb9fee8f/rmgpy/data/kinetics/family.py#L2214
I just added 'eleyrideal' in that entry, since we want one gas-phase species and one surface species as products (in the reverse of Eley Rideal). As noted in family.py above this entry, it may be better to find a way to do this without hardcoding the family name. I have not thought of a way to do that so far.
I opened a PR for this using the surfaedebug branch. @Tingchenlee, please try it and see if it works for you.

**Comment by mazeau** [comment]
I was literally just able to recreate this error when trying to test out my metal attributes pr and database using Katrin's input file for Ch4 catalytic combustion! Hurrah! And yes, adding in eleyrideal to line 2214 as seen in the surfacedebug branch does solve the problem!

**Comment by rwest** [comment]
Sounds like we have a lot of fixes for things on a lot of different branches. Which PRs should we prioritize pushing through the system and getting merged?

**Comment by mazeau** [comment]
Metal Attributes!!!!! But the surface debug is probably the simplest one because it's a one (or 2 lines, counting the comment) fix

**Comment by Tingchenlee** [comment]
I think https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2048 fix this issue now. Sorry for distracting the issue with another thermo issue. We should focus on surfacedebug branch! I'd approved the review of PR 2048.

**Comment by Tingchenlee** [comment]
Close this issue since https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2048 had been merged
