### ISSUE TITLE
Settings.py server cannot be recognized

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/RMG-database#531]
Hi,
I try to build ARC on my own workstation. Then I want it to be connected with server 'HPC'. And I don't want to any QM jobs to run on 'local'. So I only set one server in settings.py.
**servers = {
    'HPC': {
        'cluster_soft': 'PBS',
        'address': 'nus.edu.sg',
        'un': 'username',
        'key': 'my key path',
    },
}**
Then it seems that the server cannot be recognized by showing this:
**Traceback (most recent call last):
  File "/mnt/c/WSL/ARC/ARC.py", line 69, in <module>
    main()
  File "/mnt/c/WSL/ARC/ARC.py", line 64, in main
    arc_object = ARC(**input_dict)
  File "/mnt/c/WSL/ARC/arc/main.py", line 403, in __init__
    self.ess_settings = check_ess_settings(ess_settings or global_ess_settings)
  File "/mnt/c/WSL/ARC/arc/common.py", line 181, in check_ess_settings
    raise SettingsError(f'Recognized servers are {server_names}. Got: {server}')
arc.exceptions.SettingsError: Recognized servers are ['HPC']. Got: HPC**

FYI, I also build ARC on the server so I only set 'local' on there, and it is okay to run. However, when now I only set 'HPC' on my local workstation, it fails.

**Comment by alongd** [comment]
I think this issue should be open one the ARC repository, not on RMG-database. Could you close it and reopen it on ARC?

**Comment by NUSCondy** [comment]
Oh sure, sorry for putting it in the wrong place.
