### ISSUE TITLE
rmgpy.exceptions.DatabaseError: Node S6ddd points to a non-existing group called S6ddd-XdXdXd in database group

### ISSUE THREAD

**Issue by ZhouDongXi** [ReactionMechanismGenerator/RMG-database#555]
Hi, Deer RMG developments
I encountered a **rmgpy.exceptions.DatabaseError** when I tried to run a H2S oxidation reaction using RMG . The initial species are H2S CO2 and O2 and **toleranceMoveToCore** is **0.001** .The input.py is below. When the program proceeds to have 42 species and 239 reactions in core, the **rmgpy.exceptions.DatabaseError** jumped out , as show in the below picture . However, when I change the **toleranceMoveToCore** to **0.002**, the error seemed to disappear. Thank you.
![image](https://user-images.githubusercontent.com/74133930/146940706-95f30634-ba30-4ac6-9d62-fde429a1ebb7.png)

**Here is  my input.py**. 
database(
    thermoLibraries=['BurkeH2O2','thermo_DFT_CCSDTF12_BAC','primaryNS','primaryThermoLibrary'],
    reactionLibraries=['primarySulfurLibrary'],
    seedMechanisms=['BurkeH2O2inN2'],
    kineticsDepositories=['training'],
    kineticsFamilies='default',
    kineticsEstimator='rate rules',
)
species(
    label='H2S',
    reactive=True,
    structure=SMILES('S'),
)
species(
    label='CO2',
    reactive=True,
    structure=SMILES("C(=O)=O"),
)
species(
    label='O2',
    reactive=True,
    structure=SMILES('[O][O]'),
)
simpleReactor(
    temperature=(1300,'K'),
    pressure=(1,'bar'),
    initialMoleFractions={
        "H2S": 0.5,
        "CO2": 0.2,
        "O2": 0.3,
    },
    terminationTime=(2.0,'s'),
)
simulator(
    atol=1e-16,
    rtol=1e-8,
)
model(
    toleranceKeepInEdge=0,
    toleranceMoveToCore=0.001,
    toleranceInterruptSimulation=0.1,
    maximumEdgeSpecies=300000,
    filterReactions=True,
)
options(
    generateOutputHTML=True,
    generatePlots=False,
    saveEdgeSpecies=True,
    saveSimulationProfiles=False,
    saveRestartPeriod=None,
)
generatedSpeciesConstraints(
    allowed=['input species','seed mechanisms','reaction libraries'],
    maximumCarbonAtoms=5,
    maximumOxygenAtoms=4,
    maximumNitrogenAtoms=0,
    maximumSiliconAtoms=0,
    maximumSulfurAtoms=9,
    maximumHeavyAtoms=5,
    maximumRadicalElectrons=1,
    allowSingletO2=False,
)

**Comment by yunfeigaosh** [comment]
Thanks. I ran into the same problem. Please let me know if there is any update.

**Comment by ZhouDongXi** [comment]
> Hello, thank you for leaving this note. The `RMG-website` repo is for issues related to https://rmg.mit.edu/. Since this is a database issue, I am moving this to `RMG-database`.
> 
> I found that another user ran into this same issue before: see [ReactionMechanismGenerator/RMG-Py#2152](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2152). It looks like there is a bug with the sulfur thermo - I'm not sure what our status is on a fix for it yet. @rwest I saw that you were the last commenter on the issue I linked above; has anyone taken a look at this since then?

Thanks, The answer in your link fixed this bug.
