### ISSUE TITLE
Extracting kinetic parameters from Vasp barriers and vibrational frequencies 

### ISSUE THREAD

**Issue by Sudheesh1996** [ReactionMechanismGenerator/RMG-database#567]
I am a Ph.D. student from Prof. Kulkarni's group at UC Davis. We are trying to build our own kinetic and thermodynamic libraries for our systems (reactions on catalyst surface).  We have calculated barriers and vibrational frequencies of surface reactions for our system. I have the following questions,

1. Are there plans to develop an interface of VASP with RMG?
2. Is there any script available to calculate kinetic rate constants and other parameters directly from free energies and vibrational frequencies?

**Comment by cfgoldsmith** [comment]
Hi, and welcome. 
1. No, I don't think that there are any specific to develop an interface between VASP and RMG.
2. We have our own internal scripts that we use to convert the output from an electronic structure package (e.g. potential energy and vibrational frequencies) into usable input for RMG libraries. These python-based scripts are still under development, but we can share them with you. If you are using VASP as a calculator within ASE, then these scripts should be easily adaptable to your needs.

**Comment by Sudheesh1996** [comment]
Thanks for the reply and I will reach out to you through email.
