### ISSUE TITLE
The calculation method of binding energy between metal surface and C/H/O/N

### ISSUE THREAD

**Issue by utopianf** [ReactionMechanismGenerator/RMG-database#592]
I am now working on calculating the binding energy bewteen alloy and C/H/O/N. While seeing [metal.py](https://github.com/ReactionMechanismGenerator/RMG-database/blob/main/input/surface/libraries/metal.py), I noticed that there is only comment "Calculated by Katrin Blondal and Bjarne Kreitz at Brown University".
According to [RMG-py's PR](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1975), the binding energy was changed due to recent DFT calculation, is there any reference on this and how can I reproduce these values?

I will appreciate your help with this issue.

**Comment by bjkreitz** [comment]
I just looked at the metal.py file and see that the documentation is indeed very sparse. I'm going to add more information on the used DFT methods so that you can reproduce the calculations.

**Comment by utopianf** [comment]
Thanks a lot for your work!
