### ISSUE TITLE
Cannot find the reference for CH3 + O2 = CH3OO reaction at 0.01 atm in NOx 2018

### ISSUE THREAD

**Issue by agi-jaguar** [ReactionMechanismGenerator/RMG-database#613]
When I was plotting the CH3 + O2 = CH3OO reaction (MultiPdepArrhenius), I found out that k(T, P=0.01 atm) was the fastest than any other rate-coefficient at the pressure between 1-100 atm. When I deeply looked into it, the source was NOx 2018 (see attached screenshot showing NOx2018 chemkin input file). However,I couldn't find the source of k(T, P=0.01 atm) from the original NOx 2018 chemkin input file (this is from Hashemi et al., 2016's supporting information).

For some reason, when inputting this reaction rate coefficient, someone has randomly input 

PLOG/ 0.010000  6.800e+24 -3.000    0.000    /

as a kinetic coefficient info for k(T, P=0.01 atm).

I tried to find the source for this one, but couldn't locate it. My guess is that this rate coefficient is inappropriate for CH3 + O2 = CH3OO.

![image](https://user-images.github
<img width="682" alt="Screenshot 2023-03-13 at 2 02 04 PM" src="https://user-images.githubusercontent.com/122506860/224831499-4b6f7afc-dbf0-4a38-8e78-beecda2cf7a6.png">
usercontent.com/122506860/224830768-55df6255-4f3b-47b7-9184-bf1e67e1fa3e.png)

**Comment by agi-jaguar** [comment]
![index](https://user-images.githubusercontent.com/122506860/224833186-10edca0a-613b-4d2b-861c-a745c4ded5c4.png)

**Comment by agi-jaguar** [comment]
![index](https://user-images.githubusercontent.com/122506860/224833341-f311c895-2ee2-4570-adee-9f4a87985e68.png)
This is when I plot the rate coefficient that might be wrong along with other rate coefficients

**Comment by xiaoruiDong** [comment]
[The corresponding mechanism file](https://github.com/ReactionMechanismGenerator/RMG-database/files/10962169/1-s2.0-S0360128517301600-mmc3.txt)
And the relevant block:
```
CH3+O2=CH3OO                         5.0E22  -3.850    2000 ! 1 atm
 PLOG/ 0.01		             6.8E24  -3.000       0/! k0 
 PLOG/ 1.0		             5.0E22  -3.850    2000/  
 PLOG/10.0			     3.4E21  -3.200    2300/  
 PLOG/20.0                           4.1E20  -2.940    1900/  
 PLOG/20.0                           3.3E29  -5.600    6850/ 
 PLOG/50.0                           2.8E18  -2.200    1400/ 
 PLOG/50.0                           5.6E28  -5.250    6850/
 PLOG/100.0                          1.1E19  -2.300    1800/
 PLOG/100.0                          4.1E30  -5.700    8750/ 
! Fernandes RX Luther K Troe J JPCA 110:4442-4449 2006 (fit to data)
```
Source: [Fernandes et al.](https://pubs.acs.org/doi/full/10.1021/jp056850o)
The k at 0.01 atm seems to be the same as k_low reported in the source. The original kinetics used the Troe formula, but it was refitted to Plogs in this mechanism. Maybe we should directly use the Troe kinetics? Can you make a k(T, P) plot based on the Troe formula?

**Comment by xiaoruiDong** [comment]
For your convenience
![image](https://user-images.githubusercontent.com/35771233/224839850-3e320ac3-6458-4391-bb8d-0c94bd315c62.png)

**Comment by agi-jaguar** [comment]
![Troe_vs_MultiPdeP](https://user-images.githubusercontent.com/122506860/224846211-0307f912-06f0-4e6a-bfc5-74d5392f2903.png)


Hi, I think something weird happens when converting the k(T,P=0.01 atm)

You can see that the k(T,P=0.1 atm) that is estimated from k(T,P=0.01 atm) and k(T,P=1 atm) shows weird value as well.

**Comment by agi-jaguar** [comment]
I think I found the reason. For k_0, [M] has not been multiplied. 

so k_0~ 7E-31*300^3*T^-3 [cm6/#2/s] * P/RT [#/cm3] = 7E-31*300^3*1013.25/8.314E6*(6.02E23)^2 [cm6/#/s] = 8.348E+20*T^-4

When I inserted this value to the chemkin, the plot shows a good agreement now as below.

I will prepare for the git pull

![image](https://user-images.githubusercontent.com/122506860/224890175-ab1f1d3b-c1cf-4d42-bcf8-6998509867b3.png)
