### ISSUE TITLE
Duplicate reaction families? Surface_Dual_Adsorption_vdW and Surface_Abstraction_Beta_double_vdW

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-database#631]
I think that this reaction ![17840f17-2da8-457c-89c3-8c72305760bf](https://github.com/comocheng/magraf-import/assets/93807/242ed26a-f42d-43a6-973a-738d61defe78) matches the family **Surface_Dual_Adsorption_vdW**
`[<Entry index=23 label="C=C">, <Entry index=55 label="C-R">]`
![new](https://github.com/comocheng/magraf-import/assets/93807/89d9260d-d003-4c47-9cc7-56aa0161d2c5)
where R4-R6 are a C-H  (note that I am using the proposed corrected chemdraw picture, see https://github.com/ReactionMechanismGenerator/RMG-database/issues/630 )

but its reverse reaction ![088c5730-5828-4da6-88b0-2de8840031cc](https://github.com/comocheng/magraf-import/assets/93807/fca1932c-dec8-459e-9292-41f77dc9b6db) matches **Surface_Abstraction_Beta_double_vdW**  
`[<Entry index=3 label="C-H">, <Entry index=2 label="Adsorbate1">]`
![Surface_Abstraction_Beta_double_vdW](https://github.com/comocheng/magraf-import/assets/93807/c587aefb-cb46-4729-a932-728869a437b9)

The `Surface_Dual_Adsorption_vdW` family was added in  https://github.com/ReactionMechanismGenerator/RMG-database/pull/385 (specifically commit https://github.com/ReactionMechanismGenerator/RMG-database/commit/8f63ed8b74bf9adfaff32c650876f91fc8b19695)

The  `Surface_Abstraction_Beta_double_vdW` family was added in https://github.com/ReactionMechanismGenerator/RMG-database/pull/521 

Both additions seem to use this example reaction: COOH* + OH* <=> CO2* + H2O*

We should resolve this duplication (consolidate any useful data and remove one family)
and should implement database tests to detect and prevent other inadvertent duplication.

**Comment by bjkreitz** [comment]
I created the Surface_Abstraction_Beta_double_vdW family because we have BEP relations from the literature for this direction. The Surface_Dual_Adsorption_vdW family is just based on one training reaction. I trust the results from the Surface_Abstraction_Beta_double_vdW more and never used Surface_Dual_Adsorption_vdW. Therefore, I would suggest to remove Surface_Dual_Adsorption_vdW.

**Comment by rwest** [comment]
Thanks Bjarne.
The plot thickens...
Some reactions are matching _both_ **Surface_Abstraction_Beta_double_vdW** AND **Surface_Dual_Adsorption_vdW** like
![ca38f7c2-69c0-43f9-9e2b-b6bae69b8e5e](https://github.com/ReactionMechanismGenerator/RMG-database/assets/93807/d7d9f0b6-90cb-4379-a865-afe59dd44c85)
![327e970a-f30a-4eab-90ea-bacf33d6304b](https://github.com/ReactionMechanismGenerator/RMG-database/assets/93807/8509c29f-e0d9-4303-9e88-bd10ef9e5f27)
![59217589-4682-44bf-96d9-4955f99fb0aa](https://github.com/ReactionMechanismGenerator/RMG-database/assets/93807/0d52790f-3f0f-4ddd-978f-5eaa0712637f)
![89a19cc6-3b1e-4988-890d-065ad91a69c4](https://github.com/ReactionMechanismGenerator/RMG-database/assets/93807/7d867d74-aa04-44bf-9c67-80c116e40765)

But some reactions are matching _only_ **Surface_Dual_Adsorption_vdW** like
![9fd25f2a-e61e-401d-b2a8-804641fe296b](https://github.com/ReactionMechanismGenerator/RMG-database/assets/93807/4df6125a-0cb1-46cc-a495-9e60ea268a1c)
![8be58d17-33e4-4527-89ec-cacf368f6596](https://github.com/ReactionMechanismGenerator/RMG-database/assets/93807/fbae760e-0f70-45a5-8bc7-092633fb8014)
![84cd231d-c867-4075-a68f-8c731176615c](https://github.com/ReactionMechanismGenerator/RMG-database/assets/93807/33793100-4d4b-49a3-b98d-3a36058b97be)
![d6859730-3942-4eee-afeb-9227a666bb99](https://github.com/ReactionMechanismGenerator/RMG-database/assets/93807/73201c6e-0a5b-4fa9-a6ee-b28dfae800b4)

Can these reactions occur? (they do show up in Magraf's list). If so, should/can we modify **Surface_Abstraction_Beta_double_vdW** so that it matches/generates them?

**Comment by ChrisBNEU** [comment]
for the first reaction, the "abstracting" is R!H so it's disallowed. H is technically abstracting the methyl group.
```
1 *6 Xo  u0 {2,S}
2 *4 R!H u0 px cx {1,S}	
```

Second, third, and fourth, in the "donating" group, we have a double bond between *1 and *2 in the donating group. we don't allow a double bond to move to a triple.
```
1 *1 R!H u0 px cx {2,S} {4,S}
2 *2 R!H u0 px cx {1,S} {3,S}
3 *3 R   u0 {2,S}
4 *5 Xo  u0 {1,S}
```
In general, maybe we could make this family more permissive? I am not sure if that is opening us up for more junk kinetics but we should probably err on the side of allowing more.

**Comment by bjkreitz** [comment]
I think we can make the `Surface_Abstraction_Beta_double_vdW` family more permissive. However, an H atom shouldn't be able to abstract a CH3 group, but the other reactions are reasonable (although very funky). I think we should allow double bonds between 1 and 2. I'm going to update the PR.
