### ISSUE TITLE
Looks like there is a typo in rate rules file

### ISSUE THREAD

**Issue by PengZhang13** [ReactionMechanismGenerator/RMG-database#96]
Location: RMG-database\input\kinetics\families\H_Abstraction\rules.py
Line: 2038 / Entry 205
“E0 = (1.45, 'kcal/mol') “

I think it should be a negative value as -1.45

I checked the source literature. 
It looks like the parameters for this entry are taken from the rate for i-Butane T000 site. 
They were written as logA = 3.41, n = 1.9, B = -730 in the original paper. 
Then we have B*1.987/1000= -1.45
So maybe it's a typo in the rate rules file?

**Comment by connie** [comment]
Probably is a typo if the original paper says so.  Can you make the edit and create a pull request with  link to the literature source?

**Comment by nyee** [comment]
Fixed with #101
